# Generated by Django 5.0.3 on 2024-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('D', 'Desktop'), ('L', 'Laptop'), ('CL', 'Clothes'), ('E', 'Electronics'), ('FA', 'Fashion and Apparel'), ('HK', 'Home and Kitchen Appliance'), ('BC', 'Beauty and Personal Care'), ('HW', 'Health and Wellness'), ('BM', 'Books, Movies, and Music'), ('TG', 'Toys and Games'), ('SO', 'Sports and Outdoors'), ('BK', 'Baby and Kids'), ('C', 'Cars'), ('G', 'Groceries and Household Essentials'), ('OS', 'Office Supplies'), ('JW', 'Jewelry and Watches'), ('HI', 'Home Improvement and Tools')], max_length=2),
        ),
    ]
